### ISSUE TITLE
optimize the atomic/3 behaviour for batches

### ISSUE THREAD

**Issue by dongwooklee96** [ash-project/ash_paper_trail#87] opened 2024-06-25 23:55 UTC
My guess is that `ash_paper_trail` is not yet optimised for `after_batch`.

In my opinion, I think we should implement this.

**Comment by zachdaniel** [comment] 2024-08-08 18:19
closing as a duplicate of https://github.com/ash-project/ash_paper_trail/issues/40

**Closed by zachdaniel** 2024-08-08 18:19 UTC
